spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/forum
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
jwt:
  secret: secreto